POST http://localhost:3000/api/v1/contenidos
Content-Type: application/json

{
            "identificacion": "1111111110",
            "edad": 16,
            "tipo_sangre": "-O" 
}

###
POST http://localhost:3000/api/v1/aprendices/solicitud
Content-Type: application/json

{
    "nombre": "Ivan",
    "apellido": "Clavijazo",
    "email": "clavix@gmail.com",
    "formacion": "ADSO",
    "contenido": "6a58fa7d1c44ba5064e54d27"
}
